# -*- coding: utf-8 -*-
"""PaperScraper.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hgw2PF2S_jYRT-6uLs0akjJDLt9zYt5R
"""

import requests
import xml.etree.ElementTree as ET
from xml.dom import minidom

end = False
PMID_Array = []

while (end==False):
  userInput = input("For each paper you want to add, add the PMIDs, one at a time, or type 'end'.")
  if (userInput=='end'):
    end = True
  else:
    PMID_Array.append(userInput)

url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id="
for i in PMID_Array:
    url +="%2c" + i
url = url + '&retmode=xml'
#print(url)

response = requests.get(url)
with open('pubmed_result.xml', 'wb') as file:
    file.write(response.content)
    
with open('pubmed_result.xml', 'r') as file:

    tree = ET.parse(file)
    root = tree.getroot() 
    for child in root:
      PMID = child[0][0].text
      year = child.find('PubmedData').find('History')[2][0].text
      month = child.find('PubmedData').find('History')[2][1].text
      day = child.find('PubmedData').find('History')[2][2].text
      journal = child.find('MedlineCitation').find('Article').find('Journal').find('Title').text
      volume = child.find('MedlineCitation').find('Article').find('Journal').find('JournalIssue').find('Volume').text
      pagination = child.find('MedlineCitation').find('Article').find('Pagination').find('MedlinePgn').text
      doi = child.find('MedlineCitation').find('Article').find('ELocationID').text

      with open(str(year + '-' + month + '-' + day + '-' + PMID + '.md'), 'a') as PmArticle:
          PmArticle.write('---\n')
          PmArticle.write('layout: paper\n')
          PmArticle.write('title: '+ child.find('MedlineCitation').find('Article').find('ArticleTitle').text+'\n')
          PmArticle.write('image: /assets/images/papers/'+ PMID+'.jpg\n')
          
          print('\n')
          print('---\n')
          print('layout: paper\n')
          print('title: '+ child.find('MedlineCitation').find('Article').find('ArticleTitle').text+'\n')
          print('image: /assets/images/papers/'+ PMID+'.jpg\n')

          authorList = 'authors: '
          for i in child.find('MedlineCitation').find('Article').find('AuthorList').findall('Author'):
            if(len(i)>1):
              authorList += str(i[1].text + ' '+ i[0].text +', ')
          authorList = authorList[:-2]+'\n'
          PmArticle.write(authorList)
          PmArticle.write('ref: ' + child.find('MedlineCitation').find('Article').find('AuthorList').find('Author').find('LastName').text+' et al. '+ year +'. '+ journal +'.\n')
          PmArticle.write('journal: '+journal+ ' <b>'+volume+'</b>, '+ pagination + ' (' + year + ')\n')
          PmArticle.write('doi: '+doi+'\n')
          PmArticle.write('abbrev: '+journal+ ' <b>'+volume+'</b>, '+ pagination + ' (' + year + ')\n')
          PmArticle.write('pub_year: '+year+'\n')
          PmArticle.write('---\n')
          PmArticle.write('\n')
          PmArticle.write('<br />\n')
          PmArticle.write("<div data-badge-popover='right' data-badge-type='donut' data-pmid='34163070' data-hide-no-mentions='true' class='altmetric-embed'></div>\n")
          PmArticle.write('\n')
          PmArticle.write('# Abstract\n')
          PmArticle.write('\n')

          print(authorList)
          print('ref: ' + child.find('MedlineCitation').find('Article').find('AuthorList').find('Author').find('LastName').text+' et al. '+ year +'. '+ journal +'.\n')
          print('journal: '+journal+ ' <b>'+volume+'</b>, '+ pagination + ' (' + year + ')\n')
          print('doi: '+doi+'\n')
          print('abbrev: '+journal+ ' <b>'+volume+'</b>, '+ pagination + ' (' + year + ')\n')
          print('pub_year: '+year+'\n')
          print('---\n')
          print('\n')
          print('<br />\n')
          print("<div data-badge-popover='right' data-badge-type='donut' data-pmid='34163070' data-hide-no-mentions='true' class='altmetric-embed'></div>\n")
          print('\n')
          print('# Abstract\n')
          print('\n')

          text = root.find('.//AbstractText')
          PmArticle.write("".join(text.itertext())+'\n')

          print("".join(text.itertext())+'\n')

          #PmArticle.write(child.find('MedlineCitation').find('Article').find('Abstract').find('AbstractText').text+'\n')


      #print(PMID)